import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'The AI atlas',
      items: ['atlas/roadmap'],
    },
    {
      type: 'category',
      label: 'Foundations',
      items: ['foundations/ai-foundations'],
    },
    {
      type: 'category',
      label: 'Models and systems',
      items: [
        'models/transformers',
        'systems/model-lifecycle',
        'systems/inference-and-serving',
      ],
    },
    {
      type: 'category',
      label: 'Learning paradigms',
      items: ['learning/reinforcement-learning'],
    },
    {
      type: 'category',
      label: 'Knowledge systems',
      items: ['knowledge/rag', 'knowledge/rag-evaluation'],
    },
    {
      type: 'category',
      label: 'Agents and skills',
      items: ['agents/agents-agentic-skills', 'agents/skill-anatomy'],
    },
    {
      type: 'category',
      label: 'AI engineering',
      items: [
        'engineering/production-ai-engineering',
        'engineering/data-and-datasets',
        'engineering/fine-tuning-and-adaptation',
        'engineering/llmops',
        'engineering/observability',
        'engineering/quality-cost-latency',
      ],
    },
    {
      type: 'category',
      label: 'Evaluation',
      items: ['evaluation/ai-system-evaluation', 'evaluation/evaluation-design'],
    },
    {
      type: 'category',
      label: 'Trust, security, and governance',
      items: [
        'safety/trustworthy-ai',
        'safety/index',
        'safety/threat-modeling',
        'safety/prompt-injection',
        'safety/privacy-and-data',
        'safety/governance-and-standards',
        'safety/assurance-in-practice',
      ],
    },
    {
      type: 'category',
      label: 'Autonomous networks, telecom and IT',
      items: ['autonomy/autonomous-networks'],
    },
    {
      type: 'category',
      label: 'Evidence and industry',
      items: ['evidence/industry-voices'],
    },
    {
      type: 'category',
      label: 'Visuals',
      items: [
        'visual/ai-system-map',
        'visual/trustworthy-ai-system-map',
        'visuals/visual-language',
        'visuals/production-ai-system-map',
      ],
    },
    {
      type: 'category',
      label: 'Living updates',
      items: [
        'updates/index',
        'updates/sprint-03',
        'updates/sprint-04',
        'updates/sprint-05',
        'updates/sprint-06',
        'updates/update-contract',
        'updates/review-queue',
        'updates/template',
      ],
    },
    {
      type: 'category',
      label: 'Agents, skills and protocols',
      items: [
        {
      type: 'autogenerated',
      dirName: 'agents/sprint-07',
    },
  ],
},

  ],
};

export default sidebars;
