#!/usr/bin/env python3
"""Apply the public network-module and navigation upgrade idempotently."""
from pathlib import Path
import argparse
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SIDEBAR = ROOT / 'sidebars.ts'
DOCS = ROOT / 'docs'

NETWORK_CATEGORY = """    {
      type: 'category',
      label: 'Autonomous networks, telecom and IT',
      items: [
        {
          type: 'autogenerated',
          dirName: 'networks',
        },
      ],
    },
"""

REPLACEMENTS = {
    'Sprint 3 — the living intelligence layer': 'Living intelligence layer',
    'Sprint 04: the AI systems layer': 'AI systems layer',
    'Sprint 5 production AI engineering': 'Production AI engineering',
    'Sprint 6: trust, security, and governance': 'Trust, security, and governance',
    'Sprint 7: Agents and skills': 'Agents and skills',
    'Sprint 7 update': 'Agents and skills update',
    'Sprint 8': 'Multimodal and generative AI',
}


def patch_sidebar(text):
    # Remove known release-labelled update items without touching unrelated entries.
    text = re.sub(r"^\s*'updates/sprint-[^']+',?\s*\n", '', text, flags=re.M)
    text = re.sub(r"^\s*\"updates/sprint-[^\"]+\",?\s*\n", '', text, flags=re.M)
    # Remove a previously inserted duplicate category by exact block.
    text = text.replace(NETWORK_CATEGORY, '')
    if "dirName: 'networks'" not in text and 'dirName: "networks"' not in text:
        anchor = "    {\n      type: 'category',\n      label: 'Evidence and industry',"
        if anchor in text:
            text = text.replace(anchor, NETWORK_CATEGORY + anchor, 1)
        else:
            # Fall back to placing it before the final sidebar close.
            marker = "  ],\n};"
            if marker not in text:
                raise RuntimeError('Could not locate sidebar insertion point')
            text = text.replace(marker, NETWORK_CATEGORY + marker, 1)
    return text


def patch_docs():
    changed = []
    if not DOCS.exists():
        return changed
    for p in DOCS.rglob('*.md'):
        old = p.read_text(encoding='utf-8')
        new = old
        for a, b in REPLACEMENTS.items():
            new = new.replace(a, b)
        # Remove any remaining visible release word while preserving ordinary prose.
        new = re.sub(r'\bSprint\s+(?=update|layer|production|the)', '', new, flags=re.I)
        if new != old:
            p.write_text(new, encoding='utf-8')
            changed.append(str(p.relative_to(ROOT)))
    return changed


def check():
    errors = []
    if not SIDEBAR.exists():
        errors.append('sidebars.ts not found')
    else:
        s = SIDEBAR.read_text(encoding='utf-8')
        if "dirName: 'networks'" not in s and 'dirName: "networks"' not in s:
            errors.append("sidebars.ts has no networks autogenerated category")
        if re.search(r'(?i)sprint', s):
            errors.append('sidebars.ts still contains release terminology')
        if re.search(r"updates/sprint-", s):
            errors.append('sidebars.ts still references sprint update IDs')
    if DOCS.exists():
        for p in DOCS.rglob('*.md'):
            if re.search(r'(?i)\bsprint\b', p.read_text(encoding='utf-8')):
                errors.append(f'public document contains Sprint: {p.relative_to(ROOT)}')
    return errors


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    if args.check:
        errors = check()
        if errors:
            print('\n'.join('ERROR: ' + e for e in errors))
            return 1
        print('Public navigation and terminology checks passed.')
        return 0
    if SIDEBAR.exists():
        SIDEBAR.write_text(patch_sidebar(SIDEBAR.read_text(encoding='utf-8')), encoding='utf-8')
        print('Updated sidebars.ts')
    else:
        print('WARNING: sidebars.ts not found; copy the module and run again.')
    changed = patch_docs()
    print(f'Updated {len(changed)} public document(s).')
    errors = check()
    if errors:
        print('\n'.join('ERROR: ' + e for e in errors))
        return 1
    print('Upgrade applied and checks passed.')
    return 0

if __name__ == '__main__':
    sys.exit(main())
