#!/usr/bin/env python3
"""Static checks for the refreshed autonomous-networks module."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
errors = []
required = [
    'docs/networks/index.md',
    'docs/networks/autonomy/closed-loop-automation.md',
    'docs/networks/autonomy/intent-and-assurance.md',
    'docs/networks/packet-core/5g-core-architecture.md',
    'docs/networks/packet-core/packet-core-ai-use-cases.md',
    'docs/networks/cloud-native/cloud-native-network-functions.md',
    'docs/networks/operations/aiops-and-sre.md',
    'docs/networks/standards/standards-map.md',
    'docs/networks/labs/closed-loop-lab.md',
    'docs/networks/references.md',
]
for rel in required:
    p = ROOT / rel
    if not p.exists(): errors.append(f'missing {rel}')
    else:
        text = p.read_text(encoding='utf-8')
        if not text.startswith('---\n'): errors.append(f'missing front matter: {rel}')
        if re.search(r'^title:\s+[^"\'].*:', text, re.M): errors.append(f'unquoted colon in title: {rel}')
        if '$$' in text: errors.append(f'raw math block: {rel}')
        if re.search(r'\{[^\n}]+\}', text): errors.append(f'MDX expression candidate: {rel}')
        if text.count('```') % 2: errors.append(f'unbalanced code fences: {rel}')
        if re.search(r'(?i)\bsprint\b', text): errors.append(f'release terminology in module: {rel}')

# The overview deliberately has no relative links to avoid route drift; navigation is autogenerated.
overview = ROOT / 'docs/networks/index.md'
if overview.exists() and re.search(r'\]\(\.?\.?/', overview.read_text(encoding='utf-8')):
    errors.append('overview contains route-sensitive relative links')

if errors:
    print('\n'.join('ERROR: ' + e for e in errors))
    sys.exit(1)
print(f'Network refresh preflight passed for {len(required)} pages.')
