from pathlib import Path
import re, sys

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'docs' / 'data-knowledge'
errors = []
if not DOCS.exists(): errors.append('missing docs/data-knowledge directory')
files = sorted(DOCS.glob('*.md')) if DOCS.exists() else []
if len(files) < 10: errors.append(f'expected at least 10 module pages, found {len(files)}')
for path in files:
    text = path.read_text(encoding='utf-8')
    if not text.startswith('---\n'): errors.append(f'{path}: missing front matter')
    else:
        end = text.find('\n---', 4)
        if end < 0: errors.append(f'{path}: unterminated front matter')
        else:
            fm = text[4:end]
            if not re.search(r'^title:\s*"[^"\n]+"\s*$', fm, re.M): errors.append(f'{path}: title must be quoted')
            if re.search(r'^(title|sidebar_label):[^"\n]*:\s', fm, re.M): errors.append(f'{path}: unquoted colon in front matter')
    if text.count('```') % 2: errors.append(f'{path}: unbalanced code fences')
    if re.search(r'\[[^\]]+\]\(\./', text): errors.append(f'{path}: relative internal link; use autogenerated sidebar or verified route')
    for url in re.findall(r'https?://[^)\s>]+', text):
        if any(c in url for c in ['{','}','"',"'"]): errors.append(f'{path}: suspicious URL {url}')
    if re.search(r'\bSprint\b', text, re.I): errors.append(f'{path}: public release terminology found')
for required in ['index.md','references.md','lab-evidence-ledger.md']:
    if not (DOCS/required).exists(): errors.append(f'missing {required}')
if errors:
    print('\n'.join('ERROR: '+e for e in errors)); sys.exit(1)
print(f'PASS: {len(files)} data and knowledge pages validated')
